# Site settings
title: HistoryOut
description: Export and analyze your Chrome browsing history with custom date ranges. Download in CSV, JSON, or HTML formats. Free browser extension for Chrome.
url: "https://www.historyout.site"

# Theme settings
theme: jekyll-theme-cayman
show_downloads: true

# SEO settings
author:
  name: Saulius
  url: "https://www.historyout.site"

# Social links (used by jekyll-seo-tag)
social:
  name: HistoryOut
  links:
    - "https://chrome.google.com/webstore/detail/historyout/idohnkdgejocejlkihihonhemndpiiei"

# Language settings
lang: en_US

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Google Services
google_site_verification: "J9EsmoQ_afZAfv1vTpVgo5bu_xHrSMfvtdjN_fUqgrs"
google_analytics: "G-08VGKYN4DC"
